-- Script was generated by Devart Entity Developer, Version 6.0.205.0
-- Script date 5/21/2017 11:22:52 PM
-- Target Server: MySQL
-- Server Version: 5.6

-- 
-- Creating a table vrarcade.vrclienthistories 
-- 
CREATE TABLE vrarcade.vrclienthistories (
   id INT(11) NOT NULL AUTO_INCREMENT,
   starttime DATETIME NULL,
   endtime DATETIME NULL,
   tileconfigid INT(11) NOT NULL,
   vrclientid INT(11) NOT NULL,
   PRIMARY KEY (id)
);

-- 
-- Creating a table vrarcade.vrclients 
-- 
CREATE TABLE vrarcade.vrclients (
   id INT(11) NOT NULL AUTO_INCREMENT,
   machinename VARCHAR(255) NOT NULL,
   ipaddress VARCHAR(255) NOT NULL,
   dashboardmoduleip LONGTEXT NULL,
   tileconfigsetid INT(11) NOT NULL,
   isdeleted TINYINT(1) NOT NULL,
   PRIMARY KEY (id)
);

-- 
-- Creating a table vrarcade.vrconfigurations 
-- 
CREATE TABLE vrarcade.vrconfigurations (
   type VARCHAR(255) NOT NULL,
   value LONGTEXT NOT NULL,
   PRIMARY KEY (type)
);

-- 
-- Creating a table vrarcade.vrtileconfigs 
-- 
CREATE TABLE vrarcade.vrtileconfigs (
   id INT(11) NOT NULL AUTO_INCREMENT,
   tileguid VARCHAR(255) NOT NULL,
   tiletitle LONGTEXT NOT NULL,
   tileheight INT(11) NOT NULL,
   tilewidth INT(11) NOT NULL,
   agerequire INT(9) NOT NULL DEFAULT 0,
   imagedata LONGBLOB NOT NULL,
   tiledesc LONGTEXT NOT NULL,
   command LONGTEXT NOT NULL,
   arguments LONGTEXT NOT NULL,
   workingpath LONGTEXT NOT NULL,
   videourl LONGTEXT NOT NULL,
   `Order` INT(11) NOT NULL,
   tilerownumber INT(9) NOT NULL,
   tileconfigsetid INT(11) NOT NULL,
   vrtileconfigid INT(11) NOT NULL,
   isdeleted TINYINT(1) NOT NULL,
   PRIMARY KEY (id)
);

-- 
-- Creating a table vrarcade.vrtileconfigsets 
-- 
CREATE TABLE vrarcade.vrtileconfigsets (
   id INT(11) NOT NULL AUTO_INCREMENT,
   name LONGTEXT NULL,
   isdeleted TINYINT(1) NOT NULL,
   PRIMARY KEY (id)
);

-- 
-- Creating a table vrarcade.vrtickettypes 
-- 
CREATE TABLE vrarcade.vrtickettypes (
   id INT(9) NOT NULL AUTO_INCREMENT,
   type LONGTEXT NOT NULL,
   PRIMARY KEY (id)
);

-- 
-- Creating a table vrarcade.vrbookingreferences 
-- 
CREATE TABLE vrarcade.vrbookingreferences (
   id INT(9) NOT NULL AUTO_INCREMENT,
   reference LONGTEXT NOT NULL,
   isnontimedtiming TINYINT(1) NOT NULL,
   istimedtiming TINYINT(1) NOT NULL,
   duration INT(9) NOT NULL,
   numberofbookingtotal INT(9) NOT NULL,
   numberofbookingleft INT(9) NOT NULL,
   timestampcreate DATETIME NOT NULL,
   bookingchanged DATETIME NULL,
   bookingdeleted DATETIME NULL,
   bookingstarttime DATETIME NULL,
   bookingendtime DATETIME NULL,
   PRIMARY KEY (id)
);

-- 
-- Creating a table vrarcade.vrwaiverlogs 
-- 
CREATE TABLE vrarcade.vrwaiverlogs (
   id INT(9) NOT NULL AUTO_INCREMENT,
   isnewentry TINYINT(1) NOT NULL DEFAULT 1,
   firstname LONGTEXT NOT NULL,
   lastname LONGTEXT NOT NULL,
   address LONGTEXT NULL,
   city LONGTEXT NULL,
   province LONGTEXT NULL,
   postcode LONGTEXT NOT NULL,
   cell LONGTEXT NOT NULL,
   dob DATETIME NOT NULL,
   email LONGTEXT NOT NULL,
   signfilename LONGTEXT NOT NULL,
   timestampcreate DATETIME NOT NULL,
   isdeleted TINYINT(1) NOT NULL,
   bookingreferenceid INT(9) NULL,
   PRIMARY KEY (id),
   CONSTRAINT FK_vrwaiverlogs_vrbookingreferences_0 FOREIGN KEY (bookingreferenceid) REFERENCES vrarcade.vrbookingreferences (id)
);

-- 
-- Creating a table vrarcade.vrmanagelogs 
-- 
CREATE TABLE vrarcade.vrmanagelogs (
   id INT(9) NOT NULL AUTO_INCREMENT,
   operation VARCHAR(255) NOT NULL,
   additonalinfo VARCHAR(255) NULL,
   source VARCHAR(255) NOT NULL,
   sourceidentity VARCHAR(255) NOT NULL,
   `TimeStamp` DATETIME NOT NULL,
   vrclientid INT(11) NULL,
   vrtileconfigid INT(11) NULL,
   vrticketguid CHAR(36) NULL,
   PRIMARY KEY (id),
   CONSTRAINT FK_vrmanagelogs_vrclients_0 FOREIGN KEY (vrclientid) REFERENCES vrarcade.vrclients (id),
   CONSTRAINT FK_vrmanagelogs_vrtileconfigs_1 FOREIGN KEY (vrtileconfigid) REFERENCES vrarcade.vrtileconfigs (id)
);

-- 
-- Creating a table vrarcade.vrtickets 
-- 
CREATE TABLE vrarcade.vrtickets (
   guid CHAR(36) NOT NULL,
   timestampcreate DATETIME NOT NULL,
   timestampdelete DATETIME NOT NULL,
   minutes INT(9) NOT NULL DEFAULT 0,
   vrtickettypeid INT(9) NULL,
   vrclientid INT(11) NULL,
   isdeleted TINYINT(1) NOT NULL,
   waiverlogid INT(9) NULL,
   PRIMARY KEY (guid),
   CONSTRAINT FK_vrtickets_vrtickettypes_0 FOREIGN KEY (vrtickettypeid) REFERENCES vrarcade.vrtickettypes (id),
   CONSTRAINT FK_vrtickets_vrclients_1 FOREIGN KEY (vrclientid) REFERENCES vrarcade.vrclients (id),
   CONSTRAINT FK_vrtickets_vrwaiverlogs_2 FOREIGN KEY (waiverlogid) REFERENCES vrarcade.vrwaiverlogs (id)
);







-------------------------------------------------------------------------------------------------------------------

-- Insert initial data

USE vrarcade;

ALTER TABLE `vrwaiverlogs` ADD INDEX `is_new_entry` (`isnewentry`);

INSERT INTO `vrtickettypes` (`id`, `type`) VALUES
(1, 'TICKET'),
(2, 'KEY-START-NON-TIMING'),
(3, 'KEY-START-TIMING'),
(4, 'KEY-END-GAME'),
(5, 'KEY-REBOOT'),
(6, 'KEY-TURNOFF'),
(7, 'KEY-KMU-ON'),
(8, 'KEY-KMU-OFF');

INSERT INTO `vrconfigurations` (`type`, `value`) VALUES
('DEFAULT_TIMED_SESSION_LENGTH', '50'),
('DISABLE_KMU_BY_DEFAULT', 'False'),
('EMERGENCY_MESSAGE', 'Emergency Alert! \r\nPlease Exit the Building Now!'),
('LCD_BARCODE_MODULE', 'True'),
('MANUAL_END_MESSAGE', 'Your Time is Up. \r\nThanks for Playing!'),
('RE_DISABLE_KMU_AFTER_20_MIN', 'False'),
('TIMES_UP_MESSAGE', 'Your Time is Up. \r\nThanks for Playing!');


