//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using Telerik Data Access template.
// Code is generated on: 3/3/2019 8:16:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace VRGameSelectorServerDB
{
    public partial class VRClienthistory {

        public VRClienthistory()
        {
            OnCreated();
        }

        public virtual int ID
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> StartTime
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> EndTime
        {
            get;
            set;
        }

        public virtual int TileConfigID
        {
            get;
            set;
        }

        public virtual int VRClientID
        {
            get;
            set;
        }

        public virtual VRTileconfig Tileconfig
        {
            get;
            set;
        }

        public virtual VRClient VRClient
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
