//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using Telerik Data Access template.
// Code is generated on: 3/3/2019 8:16:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace VRGameSelectorServerDB
{
    public partial class VRTicket {

        public VRTicket()
        {
            this.Minutes = 0;
            this.VRManageLogs = new List<VRManageLog>();
            OnCreated();
        }

        public virtual string GUID
        {
            get;
            set;
        }

        public virtual System.DateTime TimeStampCreate
        {
            get;
            set;
        }

        public virtual System.DateTime TimeStampDelete
        {
            get;
            set;
        }

        public virtual int Minutes
        {
            get;
            set;
        }

        public virtual System.Nullable<int> VRTicketTypeID
        {
            get;
            set;
        }

        public virtual System.Nullable<int> VRClientID
        {
            get;
            set;
        }

        public virtual bool IsDeleted
        {
            get;
            set;
        }

        public virtual System.Nullable<int> WaiverLogID
        {
            get;
            set;
        }

        public virtual VRTicketType VRTicketType
        {
            get;
            set;
        }

        public virtual VRClient VRClient
        {
            get;
            set;
        }

        public virtual IList<VRManageLog> VRManageLogs
        {
            get;
            set;
        }

        public virtual VRWaiverLog WaiverLog
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
