//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using Telerik Data Access template.
// Code is generated on: 3/3/2019 8:16:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace VRGameSelectorServerDB
{
    public partial class VRArcadeDataAccessModelMetadataSource
    {
        public MappingConfiguration<VRTileconfigset> GetVRTileconfigsetMappingConfiguration()
        {
            MappingConfiguration<VRTileconfigset> configuration = this.GetVRTileconfigsetClassConfiguration();
            this.PrepareVRTileconfigsetConfigurations(configuration);
            this.OnPrepareVRTileconfigsetConfigurations(configuration);
            return configuration;
        }

        public MappingConfiguration<VRTileconfigset> GetVRTileconfigsetClassConfiguration()
        {
            MappingConfiguration<VRTileconfigset> configuration = new MappingConfiguration<VRTileconfigset>();
            configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("VRTileconfigsets");
            return configuration;
        }
	
        public void PrepareVRTileconfigsetConfigurations(MappingConfiguration<VRTileconfigset> configuration)
        {
            configuration.HasProperty(x => x.ID).ToColumn(@"ID").IsIdentity(KeyGenerator.Autoinc).WithOpenAccessType(OpenAccessType.Int32).IsNotNullable().HasPrecision(11);
            configuration.HasProperty(x => x.Name).ToColumn(@"Name").WithOpenAccessType(OpenAccessType.Clob).IsNullable().IsUnicode();
            configuration.HasProperty(x => x.IsDeleted).ToColumn(@"IsDeleted").WithOpenAccessType(OpenAccessType.Boolean).IsNotNullable();
            configuration.HasAssociation<VRClient>(x => x.Clients).WithOpposite(op => op.Tileconfigset).HasConstraint((x, y) =>  x.ID == y.TileConfigSetID);
            configuration.HasAssociation<VRTileconfig>(x => x.Tileconfigs).WithOpposite(op => op.Tileconfigset).HasConstraint((x, y) =>  x.ID == y.TileConfigSetID);
        }

        partial void OnPrepareVRTileconfigsetConfigurations(MappingConfiguration<VRTileconfigset> configuration);
    }
}
