//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using Telerik Data Access template.
// Code is generated on: 3/3/2019 8:16:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace VRGameSelectorServerDB
{
    public partial class VRWaiverLog {

        public VRWaiverLog()
        {
            this.IsNewEntry = true;
            this.VRTickets = new List<VRTicket>();
            OnCreated();
        }

        public virtual int ID
        {
            get;
            set;
        }

        public virtual bool IsNewEntry
        {
            get;
            set;
        }

        public virtual string FirstName
        {
            get;
            set;
        }

        public virtual string LastName
        {
            get;
            set;
        }

        public virtual string Address
        {
            get;
            set;
        }

        public virtual string City
        {
            get;
            set;
        }

        public virtual string Province
        {
            get;
            set;
        }

        public virtual string Postcode
        {
            get;
            set;
        }

        public virtual string Cell
        {
            get;
            set;
        }

        public virtual System.DateTime DOB
        {
            get;
            set;
        }

        public virtual string Email
        {
            get;
            set;
        }

        public virtual string SignFileName
        {
            get;
            set;
        }

        public virtual System.DateTime TimeStampCreate
        {
            get;
            set;
        }

        public virtual bool IsDeleted
        {
            get;
            set;
        }

        public virtual System.Nullable<int> BookingReferenceID
        {
            get;
            set;
        }

        public virtual IList<VRTicket> VRTickets
        {
            get;
            set;
        }

        public virtual VRBookingReference BookingReference
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
