//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using Telerik Data Access template.
// Code is generated on: 3/3/2019 8:16:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace VRGameSelectorServerDB
{
    public partial class VRTileconfig {

        public VRTileconfig()
        {
            this.AgeRequire = 0;
            this.Clienthistories = new List<VRClienthistory>();
            this.VRTileconfigs = new List<VRTileconfig>();
            this.VRManageLogs = new List<VRManageLog>();
            OnCreated();
        }

        public virtual int ID
        {
            get;
            set;
        }

        public virtual string TileGUID
        {
            get;
            set;
        }

        public virtual string TileTitle
        {
            get;
            set;
        }

        public virtual int TileHeight
        {
            get;
            set;
        }

        public virtual int TileWidth
        {
            get;
            set;
        }

        public virtual int AgeRequire
        {
            get;
            set;
        }

        public virtual byte[] ImageData
        {
            get;
            set;
        }

        public virtual string TileDesc
        {
            get;
            set;
        }

        public virtual string Command
        {
            get;
            set;
        }

        public virtual string Arguments
        {
            get;
            set;
        }

        public virtual string WorkingPath
        {
            get;
            set;
        }

        public virtual string VideoURL
        {
            get;
            set;
        }

        public virtual int Order
        {
            get;
            set;
        }

        public virtual int TileRowNumber
        {
            get;
            set;
        }

        public virtual int TileConfigSetID
        {
            get;
            set;
        }

        public virtual int VRTileconfigID
        {
            get;
            set;
        }

        public virtual bool IsDeleted
        {
            get;
            set;
        }

        public virtual IList<VRClienthistory> Clienthistories
        {
            get;
            set;
        }

        public virtual VRTileconfigset Tileconfigset
        {
            get;
            set;
        }

        public virtual IList<VRTileconfig> VRTileconfigs
        {
            get;
            set;
        }

        public virtual VRTileconfig VRTileconfig1
        {
            get;
            set;
        }

        public virtual IList<VRManageLog> VRManageLogs
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
