//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using Telerik Data Access template.
// Code is generated on: 3/3/2019 8:16:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace VRGameSelectorServerDB
{
    public partial class VRManageLog {

        public VRManageLog()
        {
            OnCreated();
        }

        public virtual int ID
        {
            get;
            set;
        }

        public virtual string Operation
        {
            get;
            set;
        }

        public virtual string AdditonalInfo
        {
            get;
            set;
        }

        public virtual string Source
        {
            get;
            set;
        }

        public virtual string SourceIdentity
        {
            get;
            set;
        }

        public virtual System.DateTime TimeStamp
        {
            get;
            set;
        }

        public virtual System.Nullable<int> VRClientID
        {
            get;
            set;
        }

        public virtual System.Nullable<int> VRTileconfigID
        {
            get;
            set;
        }

        public virtual string VRTicketGUID
        {
            get;
            set;
        }

        public virtual VRClient VRClient
        {
            get;
            set;
        }

        public virtual VRTileconfig VRTileconfig
        {
            get;
            set;
        }

        public virtual VRTicket VRTicket
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
